version: 2
jobs:
  build:
    working_directory: "~/express_template"
    docker:
      - image: "circleci/node:7.10"
    steps:
      - checkout
      - run:
        name: update-npm
        command: "sudo npm install -g npm@latest"
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
        name: install-npm-packages
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules
  test:
    docker:
      - image: "circleci/node:7.10"
    steps:
      - checkout
      - run:
        name: test
        command: "npm run test:coverage"
      - store_artifacts:
        path: coverage
        prefix: coverage

workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
        requires:
          - build
